framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        precompress:
            # possible values: 'brotli', 'zstandard', 'gzip'
            format: 'gzip'
#
#            # if you don't define the following option, AssetMapper will compress all
#            # the extensions considered safe (css, js, json, svg, xml, ttf, otf, wasm, etc.)
#            extensions: [ 'css', 'js', 'json', 'svg', 'xml' ]

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
#            precompress:
#                # possible values: 'brotli', 'zstandard', 'gzip'
#                format: 'gzip'
#
#                # if you don't define the following option, AssetMapper will compress all
#                # the extensions considered safe (css, js, json, svg, xml, ttf, otf, wasm, etc.)
#                extensions: [ 'css', 'js', 'json', 'svg', 'xml' ]
