doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'DoctrineMigrations\Sqlite': '%kernel.project_dir%/migrations/Sqlite'
        'DoctrineMigrations\Mysql': '%kernel.project_dir%/migrations/Mysql'
    enable_profiler: false
