<?php

namespace App\DataFixtures\Procrea;

use App\Entity\Enums\SeparateConceptType;
use App\Entity\SeparateConcept;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Persistence\ObjectManager;

class SeparateConceptFixtures extends Fixture implements FixtureGroupInterface
{
    public function load(ObjectManager $manager): void
    {
        $concepts = [
            [
                'type' => SeparateConceptType::Branch,
                'number' => '1',
                'formula' => null,
                'parent' => null,
                'name' => 'Materias primas y materiales',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '1.1',
                'formula' => null,
                'parent' => '1',
                'name' => 'Materiales aportados por el Constructor Estimado',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '1.2',
                'formula' => null,
                'parent' => '1',
                'name' => 'Materiales aportados por el Inversionista Estimado',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '2',
                'formula' => null,
                'parent' => null,
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '2.1',
                'formula' => null,
                'parent' => '2',
                'name' => 'Mano de Obra del Presupuesto por Renglones Variantes',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '2.2',
                'formula' => null,
                'parent' => '2',
                'name' => 'Pagos adicionales aprobados por legislación laboral',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '3',
                'formula' => null,
                'parent' => null,
                'name' => 'Uso de Equipos Por Actividad Constructiva',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '3.1',
                'formula' => null,
                'parent' => '3',
                'name' => 'Salario de Operadores',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '3.2',
                'formula' => null,
                'parent' => '3',
                'name' => 'Alquiler de Equipos',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '4',
                'formula' => null,
                'parent' => null,
                'name' => 'Otros Gastos Directos del proceso constructivo',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1',
                'formula' => null,
                'parent' => '4',
                'name' => 'Pruebas y control de calidad',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1.1',
                'formula' => null,
                'parent' => '4.1',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1.2',
                'formula' => null,
                'parent' => '4.1',
                'name' => 'Recursos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.2',
                'formula' => null,
                'parent' => '4',
                'name' => 'Mermas en el Proceso de Producción',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3',
                'formula' => null,
                'parent' => 4,
                'name' => 'Gastos en los Replanteos de las Obras',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.1',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.2',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Materiales',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.3',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de Transferencia Horizontal y Vertical de Recursos Materiales y de Equipos a Montar en el área de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4.1',
                'formula' => null,
                'parent' => '4.4',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4.2',
                'formula' => null,
                'parent' => '4.4',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5',
                'formula' => null,
                'parent' => '4',
                'name' => 'Montaje y Desmontaje de equipos de Construcción',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5.1',
                'formula' => null,
                'parent' => '4.5',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5.2',
                'formula' => null,
                'parent' => '4.5',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6',
                'formula' => null,
                'parent' => '4',
                'name' => 'Cargas y Descargas de Recursos Materiales para Construcción y Montaje y Equipos a Montar en la Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6.1',
                'formula' => null,
                'parent' => '4.6',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6.2',
                'formula' => null,
                'parent' => '4.6',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de Almacenaje de Recursos materiales y equipos a montar',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7.1',
                'formula' => null,
                'parent' => '4.7',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7.2',
                'formula' => null,
                'parent' => '4.7',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.8',
                'formula' => null,
                'parent' => '4',
                'name' => 'Paradas tecnológicas de los equipos de construcción',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.9',
                'formula' => null,
                'parent' => '4',
                'name' => 'Reparaciones y mantenimientos de otros equipos de construcción de uso común en las obras',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.10',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de protección e higiene del trabajo',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos menores de materiales, combustibles y grasas para la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11.1',
                'formula' => null,
                'parent' => '4.11',
                'name' => 'Gastos Menores (Insumos y Consuminbles)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11.2',
                'formula' => null,
                'parent' => '4.11',
                'name' => 'Combustibles y Grasas',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.12',
                'formula' => null,
                'parent' => '4',
                'name' => 'Herramientas',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.13',
                'formula' => null,
                'parent' => '4',
                'name' => 'Electricidad al servicio de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.14',
                'formula' => null,
                'parent' => '4',
                'name' => 'Agua al servicio de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos relacionados con la limpieza de la Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15.1',
                'formula' => null,
                'parent' => '4.15',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15.2',
                'formula' => null,
                'parent' => '4.15',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.16',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de aseo de los trabajadores',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17',
                'formula' => null,
                'parent' => '4',
                'name' => 'Dirección de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.1',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Salarios (Técnico-Ejecutor-Jefe de Grupo-Chofer)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.2',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Comunicaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.3',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Transportación',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.4',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Combustible',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.5',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Material de Oficina',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.6',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Otros Gastos necesarios',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de preparación y asimilación de la producción',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1',
                'formula' => null,
                'parent' => '4.18',
                'name' => 'Gastos de Preparación Técnica y Elaboración de Ofertas',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.1',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Salarios (Técnico-Presupuestistas-Ingenieros-Proyectistas-Chofer)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.2',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Comunicaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.3',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Transportación',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.4',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Combustible',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.5',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Material de Oficina',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.6',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Otros Gastos necesarios',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2',
                'formula' => null,
                'parent' => '4.18',
                'name' => 'Gastos de Comercialización para la entrega de Materiales a la Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.1',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Salarios (Gestionador Comprador-Logísitico de Obra-Chofer)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.2',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Comunicaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.3',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Transportación',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.4',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Combustible',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.5',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Material de Oficina',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.6',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Otros Gastos necesarios',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '5',
                'formula' => '1+2+3+4',
                'parent' => null,
                'name' => 'Costos Directos de Producción',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '6',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Asociados a la Producción de la Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1',
                'formula' => null,
                'parent' => '6',
                'name' => 'Gastos de la fuerza de trabajo (técnicos y directivos de la producción no vinculados a un producto o servicio)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.1',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Salarios (Otros, Jefe de Grupo)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.2',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Comunicaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.3',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Transportación',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.4',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Combustible',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.5',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Material de Oficina',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.6',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Otros Gastos necesarios',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.2',
                'formula' => null,
                'parent' => '6',
                'name' => 'Otros Gastos (Mantenimiento, reparaciones corrientes y depreciación de instalaciones productivas, Amortización y depreciación de los activos fijos tangibles de producción, Desgastes de Útiles y Herramientas)',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '7',
                'formula' => '5+6',
                'parent' => null,
                'name' => 'Total de Costos de Producción de la Obra',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '8',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Generales y de Administración',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.1',
                'formula' => null,
                'parent' => '8',
                'name' => 'Salarios de la Administración General',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.1',
                'formula' => null,
                'parent' => '8',
                'name' => 'Salarios de la Administración General',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.2',
                'formula' => null,
                'parent' => '8',
                'name' => 'Comunicaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.3',
                'formula' => null,
                'parent' => '8',
                'name' => 'Arrendamiento del Transporte y Traslado de Personal',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.4',
                'formula' => null,
                'parent' => '8',
                'name' => 'Combustible',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.5',
                'formula' => null,
                'parent' => '8',
                'name' => 'Material de Oficina',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.6',
                'formula' => null,
                'parent' => '8',
                'name' => 'Otros Gastos necesarios',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '9',
                'formula' => '6+8',
                'parent' => null,
                'name' => 'Gastos Indirectos',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '10',
                'formula' => null,
                'parent' => null,
                'name' => 'Otros Conceptos de Gastos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1',
                'formula' => null,
                'parent' => '10',
                'name' => 'Facilidades Temporales',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.1',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.2',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Edificaciones e instalaciones provisionales necesarias para la ejecución de la obra construídas o montadas en obra y  Materiales para su construcción',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.3',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.4',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Activos Fijos (Contenedores, Tanques de Agua, Tanques de Desperdicio y Elementos Modulares de la empresa)',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2',
                'formula' => null,
                'parent' => '10',
                'name' => 'Transportación de Suministros y Medios a la Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2.1',
                'formula' => null,
                'parent' => '10.2',
                'name' => 'Transportación',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2.2',
                'formula' => null,
                'parent' => '10.2',
                'name' => 'Combustibles',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3',
                'formula' => null,
                'parent' => '10',
                'name' => 'Imprevistos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.1',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Mano de Obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.2',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Materiales',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.3',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Uso de Equipos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.4',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Otros gastos directos del proceso constructivo',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.5',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Transportación de suministros y medios a la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4',
                'formula' => null,
                'parent' => '10',
                'name' => 'Otras Partidas que se requieran de acuerdo  con las características de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.1',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Transporte de operarios directos a la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.2',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Transporte de personal, pase y vacaciones',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.3',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Gastos de Almuerzos',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.4',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Gastos de alojamiento y albergues',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.5',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Otros Gastos de Transporte',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.6',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Servicio de vigilancia y seguridad de la obra',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.7',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Otros',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '11',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Financieros',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '11.1',
                'formula' => null,
                'parent' => '11',
                'name' => 'Intereses',
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '11.2',
                'formula' => null,
                'parent' => '11',
                'name' => 'Comisiones Bancarias',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '12',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos por financiamiento entregado a la OSDE',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Tributarios',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13.1',
                'formula' => null,
                'parent' => '13',
                'name' => 'Impuesto por el Uso de la Fuerza de Trabajo (5% del total de salarios)',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13.2',
                'formula' => null,
                'parent' => '13',
                'name' => 'Contribución a la Seguridad Social a corto y largo plazos',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '14',
                'formula' => '8+10+11+12+13',
                'parent' => null,
                'name' => 'Total de Gastos de la Obra',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '15',
                'formula' => '5+9+10+11+12+13',
                'parent' => null,
                'name' => 'Total de Costos y Gastos',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '16',
                'formula' => '(2+3+4+6)%15',
                'parent' => null,
                'name' => 'Utilidad',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '17',
                'formula' => '15+16',
                'parent' => null,
                'name' => 'Precio del Servicio de Construcción',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '18',
                'formula' => '17-1.2',
                'parent' => null,
                'name' => 'A Cobrar',
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '19',
                'formula' => null,
                'parent' => null,
                'name' => 'Impuestos sobre ventas autorizados por MFP',
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '20',
                'formula' => '18+19',
                'parent' => null,
                'name' => 'Facturación del Servicio',
            ],
        ];
        foreach ($concepts as $concept) {
            $conceptEntity = $manager->getRepository(SeparateConcept::class)->findOneBy(['name' => $concept['name']]);
            if (is_null($conceptEntity)) {
                $conceptEntity = new SeparateConcept();
                $conceptEntity->setName($concept['name']);
                $conceptEntity->setType($concept['type']);
                $conceptEntity->setNumber($concept['number']);
                $conceptEntity->setFormula($concept['formula']);
                if (!is_null($concept['parent'])) {
                    $parentConcept = $manager->getRepository(SeparateConcept::class)->findOneBy(['number' => $concept['parent']]);
                    if (!is_null($parentConcept)) {
                        $conceptEntity->setParent($parentConcept);
                    }
                }

                $manager->persist($conceptEntity);
                $manager->flush();
            }
        }

        $manager->flush();
    }

    public static function getGroups(): array
    {
        return ['procrea'];
    }
}
