<?php

namespace App\DataFixtures\Procrea;

use App\Entity\Enums\SeparateConceptType;
use App\Entity\SeparateConcept;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Persistence\ObjectManager;

class SeparateConceptFixtures extends Fixture implements FixtureGroupInterface
{
    public function load(ObjectManager $manager): void
    {
        $concepts = [
            [
                'type' => SeparateConceptType::Branch,
                'number' => '1',
                'formula' => null, // cuando la formula es nula, es la sumatorio de todos los hijos
                'parent' => null,
                'name' => 'Materias primas y materiales',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '1.1',
                'formula' => null,
                'parent' => '1',
                'name' => 'Materiales aportados por el Constructor Estimado',
                'percent' => 90,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '1.2',
                'formula' => null,
                'parent' => '1',
                'name' => 'Materiales aportados por el Inversionista Estimado',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '2',
                'formula' => null,
                'parent' => null,
                'name' => 'Mano de Obra',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '2.1',
                'formula' => null,
                'parent' => '2',
                'name' => 'Mano de Obra del Presupuesto por Renglones Variantes',
                'percent' => 90,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '2.2',
                'formula' => null,
                'parent' => '2',
                'name' => 'Pagos adicionales aprobados por legislación laboral',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '3',
                'formula' => null,
                'parent' => null,
                'name' => 'Uso de Equipos Por Actividad Constructiva',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '3.1',
                'formula' => null,
                'parent' => '3',
                'name' => 'Salario de Operadores',
                'percent' => 25,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '3.2',
                'formula' => null,
                'parent' => '3',
                'name' => 'Alquiler de Equipos',
                'percent' => 75,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '4',
                'formula' => null,
                'parent' => null,
                'name' => 'Otros Gastos Directos del proceso constructivo',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1',
                'formula' => null,
                'parent' => '4',
                'name' => 'Pruebas y control de calidad',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1.1',
                'formula' => null,
                'parent' => '4.1',
                'name' => 'Mano de Obra',
                'percent' => 90,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.1.2',
                'formula' => null,
                'parent' => '4.1',
                'name' => 'Recursos',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.2',
                'formula' => null,
                'parent' => '4',
                'name' => 'Mermas en el Proceso de Producción',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3',
                'formula' => null,
                'parent' => 4,
                'name' => 'Gastos en los Replanteos de las Obras',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.1',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Mano de Obra',
                'percent' => 50,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.2',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Materiales',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.3.3',
                'formula' => null,
                'parent' => '4.3',
                'name' => 'Equipos',
                'percent' => 30,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de Transferencia Horizontal y Vertical de Recursos Materiales y de Equipos a Montar en el área de la obra',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4.1',
                'formula' => null,
                'parent' => '4.4',
                'name' => 'Mano de Obra',
                'percent' => 80,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.4.2',
                'formula' => null,
                'parent' => '4.4',
                'name' => 'Equipos',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5',
                'formula' => null,
                'parent' => '4',
                'name' => 'Montaje y Desmontaje de equipos de Construcción',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5.1',
                'formula' => null,
                'parent' => '4.5',
                'name' => 'Mano de Obra',
                'percent' => 80,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.5.2',
                'formula' => null,
                'parent' => '4.5',
                'name' => 'Equipos',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6',
                'formula' => null,
                'parent' => '4',
                'name' => 'Cargas y Descargas de Recursos Materiales para Construcción y Montaje y Equipos a Montar en la Obra',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6.1',
                'formula' => null,
                'parent' => '4.6',
                'name' => 'Mano de Obra',
                'percent' => 80,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.6.2',
                'formula' => null,
                'parent' => '4.6',
                'name' => 'Equipos',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de Almacenaje de Recursos materiales y equipos a montar',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7.1',
                'formula' => null,
                'parent' => '4.7',
                'name' => 'Mano de Obra',
                'percent' => 80,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.7.2',
                'formula' => null,
                'parent' => '4.7',
                'name' => 'Equipos',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.8',
                'formula' => null,
                'parent' => '4',
                'name' => 'Paradas tecnológicas de los equipos de construcción',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.9',
                'formula' => null,
                'parent' => '4',
                'name' => 'Reparaciones y mantenimientos de otros equipos de construcción de uso común en las obras',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.10',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de protección e higiene del trabajo',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos menores de materiales, combustibles y grasas para la obra',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11.1',
                'formula' => null,
                'parent' => '4.11',
                'name' => 'Gastos Menores (Insumos y Consuminbles)',
                'percent' => 90,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.11.2',
                'formula' => null,
                'parent' => '4.11',
                'name' => 'Combustibles y Grasas',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.12',
                'formula' => null,
                'parent' => '4',
                'name' => 'Herramientas',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.13',
                'formula' => null,
                'parent' => '4',
                'name' => 'Electricidad al servicio de la obra',
                'percent' => 1,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.14',
                'formula' => null,
                'parent' => '4',
                'name' => 'Agua al servicio de la obra',
                'percent' => 1,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos relacionados con la limpieza de la Obra',
                'percent' => 6,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15.1',
                'formula' => null,
                'parent' => '4.15',
                'name' => 'Mano de Obra',
                'percent' => 90,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.15.2',
                'formula' => null,
                'parent' => '4.15',
                'name' => 'Equipos',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.16',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de aseo de los trabajadores',
                'percent' => 1,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17',
                'formula' => null,
                'parent' => '4',
                'name' => 'Dirección de la obra',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.1',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Salarios (Técnico-Ejecutor-Jefe de Grupo-Chofer)',
                'percent' => 50,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.2',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Comunicaciones',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.3',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Transportación',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.4',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Combustible',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.5',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Material de Oficina',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.17.6',
                'formula' => null,
                'parent' => '4.17',
                'name' => 'Otros Gastos necesarios',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18',
                'formula' => null,
                'parent' => '4',
                'name' => 'Gastos de preparación y asimilación de la producción',
                'percent' => 8,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1',
                'formula' => null,
                'parent' => '4.18',
                'name' => 'Gastos de Preparación Técnica y Elaboración de Ofertas',
                'percent' => 57.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.1',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Salarios (Técnico-Presupuestistas-Ingenieros-Proyectistas-Chofer)',
                'percent' => 35,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.2',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Comunicaciones',
                'percent' => 2.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.3',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Transportación',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.4',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Combustible',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.5',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Material de Oficina',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.1.6',
                'formula' => null,
                'parent' => '4.18.1',
                'name' => 'Otros Gastos necesarios',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2',
                'formula' => null,
                'parent' => '4.18',
                'name' => 'Gastos de Comercialización para la entrega de Materiales a la Obra',
                'percent' => 42.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.1',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Salarios (Gestionador Comprador-Logísitico de Obra-Chofer)',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.2',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Comunicaciones',
                'percent' => 2.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.3',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Transportación',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.4',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Combustible',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.5',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Material de Oficina',
                'percent' => 2.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '4.18.2.6',
                'formula' => null,
                'parent' => '4.18.2',
                'name' => 'Otros Gastos necesarios',
                'percent' => 2.5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '5',
                'formula' => '1+2+3+4', // suma de los %
                'parent' => null,
                'name' => 'Costos Directos de Producción',
                'percent' => null, // si no tiene hijos, debo guiarme con la suma de la formula de sus %
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '6',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Asociados a la Producción de la Obra',
                'percent' => 3,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1',
                'formula' => null,
                'parent' => '6',
                'name' => 'Gastos de la fuerza de trabajo (técnicos y directivos de la producción no vinculados a un producto o servicio)',
                'percent' => 75,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.1',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Salarios (Otros, Jefe de Grupo)',
                'percent' => 50,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.2',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Comunicaciones',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.3',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Transportación',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.4',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Combustible',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.5',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Material de Oficina',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.1.6',
                'formula' => null,
                'parent' => '6.1',
                'name' => 'Otros Gastos necesarios',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '6.2',
                'formula' => null,
                'parent' => '6',
                'name' => 'Otros Gastos (Mantenimiento, reparaciones corrientes y depreciación de instalaciones productivas, Amortización y depreciación de los activos fijos tangibles de producción, Desgastes de Útiles y Herramientas)',
                'percent' => 25,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '7',
                'formula' => '5+6',
                'parent' => null,
                'name' => 'Total de Costos de Producción de la Obra',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '8',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Generales y de Administración',
                'percent' => 8,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.1',
                'formula' => null,
                'parent' => '8',
                'name' => 'Salarios de la Administración General',
                'percent' => 50,
                'ignore' => null,
            ],
            /*[
                'type' => SeparateConceptType::Leaf,
                'number' => '8.1',
                'formula' => null,
                'parent' => '8',
                'name' => 'Salarios de la Administración General',
            ],*/
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.2',
                'formula' => null,
                'parent' => '8',
                'name' => 'Comunicaciones',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.3',
                'formula' => null,
                'parent' => '8',
                'name' => 'Arrendamiento del Transporte y Traslado de Personal',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.4',
                'formula' => null,
                'parent' => '8',
                'name' => 'Combustible',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.5',
                'formula' => null,
                'parent' => '8',
                'name' => 'Material de Oficina',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '8.6',
                'formula' => null,
                'parent' => '8',
                'name' => 'Otros Gastos necesarios',
                'percent' => 5,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '9',
                //                'formula' => '(6+8)/(2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1)',
                'formula' => '6+8',
                'parent' => null,
                'name' => 'Gastos Indirectos',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '10',
                'formula' => null,
                'parent' => null,
                'name' => 'Otros Conceptos de Gastos',
                'percent' => 8,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1',
                'formula' => null,
                'parent' => '10',
                'name' => 'Facilidades Temporales',
                'percent' => 25,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.1',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Mano de Obra',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.2',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Edificaciones e instalaciones provisionales necesarias para la ejecución de la obra construídas o montadas en obra y  Materiales para su construcción',
                'percent' => 50,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.3',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Equipos',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.1.4',
                'formula' => null,
                'parent' => '10.1',
                'name' => 'Activos Fijos (Contenedores, Tanques de Agua, Tanques de Desperdicio y Elementos Modulares de la empresa)',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2',
                'formula' => null,
                'parent' => '10',
                'name' => 'Transportación de Suministros y Medios a la Obra',
                'percent' => 50,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2.1',
                'formula' => null,
                'parent' => '10.2',
                'name' => 'Transportación',
                'percent' => 80,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.2.2',
                'formula' => null,
                'parent' => '10.2',
                'name' => 'Combustibles',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3',
                'formula' => null,
                'parent' => '10',
                'name' => 'Imprevistos',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.1',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Mano de Obra',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.2',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Materiales',
                'percent' => 50,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.3',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Uso de Equipos',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.4',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Otros gastos directos del proceso constructivo',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.3.5',
                'formula' => null,
                'parent' => '10.3',
                'name' => 'Transportación de suministros y medios a la obra',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4',
                'formula' => null,
                'parent' => '10',
                'name' => 'Otras Partidas que se requieran de acuerdo  con las características de la obra',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.1',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Transporte de operarios directos a la obra',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.2',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Transporte de personal, pase y vacaciones',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.3',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Gastos de Almuerzos',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.4',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Gastos de alojamiento y albergues',
                'percent' => 20,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.5',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Otros Gastos de Transporte',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.6',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Servicio de vigilancia y seguridad de la obra',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '10.4.7',
                'formula' => null,
                'parent' => '10.4',
                'name' => 'Otros',
                'percent' => 10,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '11',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos Financieros',
                'percent' => 0.1,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '11.1',
                'formula' => null,
                'parent' => '11',
                'name' => 'Intereses',
                'percent' => 15,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Leaf,
                'number' => '11.2',
                'formula' => null,
                'parent' => '11',
                'name' => 'Comisiones Bancarias',
                'percent' => 85,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '12',
                'formula' => null,
                'parent' => null,
                'name' => 'Gastos por financiamiento entregado a la OSDE',
                'percent' => 0.1,
                'ignore' => null,
            ],
            //            [
            //                'type' => SeparateConceptType::Computable,
            //                'number' => '13',
            //                'formula' => '2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1+6.1.1+8.1+10.1.1+10.3.1',
            //                'parent' => null,
            //                'name' => 'Fondo de salario',
            //                'percent' => null,
            //                'ignore' => null,
            //            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13',
                'formula' => '((2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1+6.1.1+8.1+10.1.1+10.3.1)*5/100)+((2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1+6.1.1+8.1+10.1.1+10.3.1)*14/100)',
                'parent' => null,
                'name' => 'Gastos Tributarios',
                'percent' => null,
                'ignore' => [5, 14, 100],
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13.1',
                'formula' => '(2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1+6.1.1+8.1+10.1.1+10.3.1)*5/100',
                'parent' => '13',
                'name' => 'Impuesto por el Uso de la Fuerza de Trabajo (5% del total de salarios)',
                'percent' => null,
                'ignore' => [5, 100],
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '13.2',
                'formula' => '(2+3.1+4.1.1+4.3.1+4.4.1+4.5.1+4.6.1+4.7.1+4.15.1+4.17.1+4.18.1.1+4.18.2.1+6.1.1+8.1+10.1.1+10.3.1)*14/100',
                'parent' => '13',
                'name' => 'Contribución a la Seguridad Social a corto y largo plazos (14% del total de salarios)',
                'percent' => null,
                'ignore' => [14, 100],
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '14',
                'formula' => '8+10+11+12+13',
                'parent' => null,
                'name' => 'Total de Gastos de la Obra',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '15',
                'formula' => '5+9+10+11+12+13',
                'parent' => null,
                'name' => 'Total de Costos y Gastos',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '16',
                'formula' => '(2+3+4+6)*15/100',
                'parent' => null,
                'name' => 'Utilidad',
                'percent' => null,
                'ignore' => ['15', '100'],
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '17',
                'formula' => '15+16',
                'parent' => null,
                'name' => 'Precio del Servicio de Construcción',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '18',
                'formula' => '17-1.2',
                'parent' => null,
                'name' => 'A Cobrar',
                'percent' => null,
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Branch,
                'number' => '19',
                'formula' => null,
                'parent' => null,
                'name' => 'Impuestos sobre ventas autorizados por MFP',
                'percent' => 10, // del total
                'ignore' => null,
            ],
            [
                'type' => SeparateConceptType::Computable,
                'number' => '20',
                'formula' => '1+2+3+4+6+8+10+11+12+13+16+19',
                'parent' => null,
                'name' => 'Facturación del Servicio',
                'percent' => null,
                'ignore' => null,
            ],
        ];
        foreach ($concepts as $concept) {
            //            $conceptEntity = $manager->getRepository(SeparateConcept::class)->findOneBy(['name' => $concept['name']]);
            //            if (is_null($conceptEntity)) {
            $conceptEntity = new SeparateConcept();
            $conceptEntity->setName($concept['name']);
            $conceptEntity->setType($concept['type']);
            $conceptEntity->setNumber($concept['number']);
            $conceptEntity->setFormula($concept['formula']);
            $conceptEntity->setPercent($concept['percent']);
            if (isset($concept['ignore'])) {
                $conceptEntity->setIgnoreNumber($concept['ignore']);
            }
            if (!is_null($concept['parent'])) {
                $parentConcept = $manager->getRepository(SeparateConcept::class)->findOneBy(['number' => $concept['parent']]);
                if (!is_null($parentConcept)) {
                    $conceptEntity->setParent($parentConcept);
                }
            }

            $manager->persist($conceptEntity);
            $manager->flush();
            //            }
        }

        $manager->flush();
    }

    public static function getGroups(): array
    {
        return ['procrea'];
    }
}
